[build]
  command = "pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Dodatkowe przekierowania dla SEO
[[redirects]]
  from = "/about"
  to = "/o-nas"
  status = 301

# Przekierowanie dla ścieżek bez końcowego slasha
[[redirects]]
  from = "/o-nas/"
  to = "/o-nas"
  status = 301

[[redirects]]
  from = "/tiktok/"
  to = "/tiktok"
  status = 301

[[redirects]]
  from = "/kontakt/"
  to = "/kontakt"
  status = 301